# Predicting House Prices

## Problem Definition

State the business problem. Translate the business problem into a Data Science problem by stating what kind of problem it is ( supervised vs unsupervised ) and whether it is a classification, regression, or clustering problem.

We want to predict the sales prices of a home given a number of the property's features.

- there is a target
- supervised learning
- the target is SalePrice, which is numerical, continuous
- regression

This is a supervised, regression problem and we'll be using Linear Regression to make the predictions.  We'll also be using Ridge and Lasso regularization techniques to reduce overfitting and for feature selection.  Our performance metric with be RMSPE.

## Data Collection/Sources

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### IDA

In [1]:
url = "https://ddc-datascience.s3.amazonaws.com/Projects/Project.2-Housing/Data/Housing.Data.csv"
url

'https://ddc-datascience.s3.amazonaws.com/Projects/Project.2-Housing/Data/Housing.Data.csv'

In [3]:
!curl -s -I {url} | grep -i -e ^http -e type: -e length:

HTTP/1.1 200 OK
Content-Type: text/csv
Content-Length: 880420

In [4]:
!curl -s {url} | head -n 2

PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Roof Style,Roof Matl,Exterior 1st,Exterior 2nd,Mas Vnr Type,Mas Vnr Area,Exter Qual,Exter Cond,Foundation,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin SF 1,BsmtFin Type 2,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,Heating,Heating QC,Central Air,Electrical,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,Kitchen Qual,TotRms AbvGrd,Functional,Fireplaces,Fireplace Qu,Garage Type,Garage Yr Blt,Garage Finish,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
905101070,20,RL,62.0,14299,Pave,,Reg,Lvl,AllPub,Inside,Gtl,Sawyer,Feedr,Norm,1Fam,1Story,4,3,1964,1964,Gable,CompShg,HdBoard,HdBoard,None,0.0,TA,TA,CBlock,TA,TA,No,Rec,513.0,LwQ,144.0,348.0,1005.0,GasA,TA,Y,SBrkr,1005,0,0,1005,1.0,0.0,1,0,3,1,TA,5,Typ,0,,Detchd,1964.0,Unf,2.0,440.0,TA,TA,N,0,0,0,0,0,0,,MnPrv,,0,7,2007,WD ,Normal,115400

### Reading in the data

In [7]:
df = pd.read_csv( url )
df

            PID  MS SubClass MS Zoning  ...  Sale Type  Sale Condition SalePrice
0     905101070           20        RL  ...        WD           Normal    115400
1     905101330           90        RL  ...        WD           Normal     90000
2     903454090           50        RM  ...        WD           Normal    141000
3     533244030           60        FV  ...        WD           Normal    254000
4     909252020           70        RL  ...        WD           Normal    155000
...         ...          ...       ...  ...        ...             ...       ...
2632  903231070           50        RM  ...        WD           Normal    114500
2633  906201021           80        RL  ...        WD           Normal    162000
2634  533253070          120        RL  ...        WD           Normal    211500
2635  527376100           20        RL  ...        WD           Normal    165000
2636  528292060           60        RL  ...        WD           Normal    225000

[2637 rows x 81 columns]

In [13]:
df.shape

(2637, 81)

In [14]:
df.head()

         PID  MS SubClass MS Zoning  ...  Sale Type  Sale Condition SalePrice
0  905101070           20        RL  ...        WD           Normal    115400
1  905101330           90        RL  ...        WD           Normal     90000
2  903454090           50        RM  ...        WD           Normal    141000
3  533244030           60        FV  ...        WD           Normal    254000
4  909252020           70        RL  ...        WD           Normal    155000

[5 rows x 81 columns]

In [15]:
df.tail()

            PID  MS SubClass MS Zoning  ...  Sale Type  Sale Condition SalePrice
2632  903231070           50        RM  ...        WD           Normal    114500
2633  906201021           80        RL  ...        WD           Normal    162000
2634  533253070          120        RL  ...        WD           Normal    211500
2635  527376100           20        RL  ...        WD           Normal    165000
2636  528292060           60        RL  ...        WD           Normal    225000

[5 rows x 81 columns]

#### Columns

In [20]:
list(enumerate(df.columns.to_list(), start=100))

[(100, 'PID'),
 (101, 'MS SubClass'),
 (102, 'MS Zoning'),
 (103, 'Lot Frontage'),
 (104, 'Lot Area'),
 (105, 'Street'),
 (106, 'Alley'),
 (107, 'Lot Shape'),
 (108, 'Land Contour'),
 (109, 'Utilities'),
 (110, 'Lot Config'),
 (111, 'Land Slope'),
 (112, 'Neighborhood'),
 (113, 'Condition 1'),
 (114, 'Condition 2'),
 (115, 'Bldg Type'),
 (116, 'House Style'),
 (117, 'Overall Qual'),
 (118, 'Overall Cond'),
 (119, 'Year Built'),
 (120, 'Year Remod/Add'),
 (121, 'Roof Style'),
 (122, 'Roof Matl'),
 (123, 'Exterior 1st'),
 (124, 'Exterior 2nd'),
 (125, 'Mas Vnr Type'),
 (126, 'Mas Vnr Area'),
 (127, 'Exter Qual'),
 (128, 'Exter Cond'),
 (129, 'Foundation'),
 (130, 'Bsmt Qual'),
 (131, 'Bsmt Cond'),
 (132, 'Bsmt Exposure'),
 (133, 'BsmtFin Type 1'),
 (134, 'BsmtFin SF 1'),
 (135, 'BsmtFin Type 2'),
 (136, 'BsmtFin SF 2'),
 (137, 'Bsmt Unf SF'),
 (138, 'Total Bsmt SF'),
 (139, 'Heating'),
 (140, 'Heating QC'),
 (141, 'Central Air'),
 (142, 'Electrical'),
 (143, '1st Flr SF'),
 (144, '2nd Flr SF'),
 (145, 'Low Qual Fin SF'),
 (146, 'Gr Liv Area'),
 (147, 'Bsmt Full Bath'),
 (148, 'Bsmt Half Bath'),
 (149, 'Full Bath'),
 (150, 'Half Bath'),
 (151, 'Bedroom AbvGr'),
 (152, 'Kitchen AbvGr'),
 (153, 'Kitchen Qual'),
 (154, 'TotRms AbvGrd'),
 (155, 'Functional'),
 (156, 'Fireplaces'),
 (157, 'Fireplace Qu'),
 (158, 'Garage Type'),
 (159, 'Garage Yr Blt'),
 (160, 'Garage Finish'),
 (161, 'Garage Cars'),
 (162, 'Garage Area'),
 (163, 'Garage Qual'),
 (164, 'Garage Cond'),
 (165, 'Paved Drive'),
 (166, 'Wood Deck SF'),
 (167, 'Open Porch SF'),
 (168, 'Enclosed Porch'),
 (169, '3Ssn Porch'),
 (170, 'Screen Porch'),
 (171, 'Pool Area'),
 (172, 'Pool QC'),
 (173, 'Fence'),
 (174, 'Misc Feature'),
 (175, 'Misc Val'),
 (176, 'Mo Sold'),
 (177, 'Yr Sold'),
 (178, 'Sale Type'),
 (179, 'Sale Condition'),
 (180, 'SalePrice')]

In [24]:
df.dtypes.value_counts()

object     43
int64      27
float64    11
Name: count, dtype: int64

In [23]:
pd.set_option('display.max_rows', 100)
df.dtypes.sort_values()

PID                  int64
Low Qual Fin SF      int64
Gr Liv Area          int64
Full Bath            int64
Half Bath            int64
Bedroom AbvGr        int64
Kitchen AbvGr        int64
TotRms AbvGrd        int64
Fireplaces           int64
Wood Deck SF         int64
Open Porch SF        int64
Enclosed Porch       int64
3Ssn Porch           int64
Screen Porch         int64
Pool Area            int64
Misc Val             int64
Mo Sold              int64
Yr Sold              int64
2nd Flr SF           int64
1st Flr SF           int64
SalePrice            int64
Lot Area             int64
Overall Cond         int64
MS SubClass          int64
Overall Qual         int64
Year Remod/Add       int64
Year Built           int64
Bsmt Unf SF        float64
BsmtFin SF 2       float64
BsmtFin SF 1       float64
Garage Area        float64
Bsmt Full Bath     float64
Total Bsmt SF      float64
Garage Cars        float64
Mas Vnr Area       float64
Lot Frontage       float64
Garage Yr Blt      float64
Bsmt Half Bath     float64
Garage Finish       object
Garage Type         object
Garage Qual         object
Roof Style          object
Paved Drive         object
Utilities           object
Fireplace Qu        object
Land Contour        object
Lot Shape           object
Alley               object
Street              object
Pool QC             object
Fence               object
Misc Feature        object
MS Zoning           object
Sale Type           object
Garage Cond         object
Lot Config          object
Condition 2         object
Land Slope          object
Roof Matl           object
Exterior 1st        object
Exterior 2nd        object
Mas Vnr Type        object
Exter Qual          object
Exter Cond          object
Foundation          object
Bsmt Qual           object
Bsmt Cond           object
Bsmt Exposure       object
BsmtFin Type 1      object
BsmtFin Type 2      object
Heating             object
Sale Condition      object
Central Air         object
Electrical          object
House Style         object
Bldg Type           object
Condition 1         object
Neighborhood        object
Kitchen Qual        object
Functional          object
Heating QC          object
dtype: object

## Data Cleaning

### Examine target

In [12]:
df[["SalePrice"]]

      SalePrice
0        115400
1         90000
2        141000
3        254000
4        155000
...         ...
2632     114500
2633     162000
2634     211500
2635     165000
2636     225000

[2637 rows x 1 columns]

In [8]:
df["SalePrice"].isnull().sum()

np.int64(0)

In [9]:
df["SalePrice"].dtype

dtype('int64')

### Examine features

#### Unique IDs

#### Floats

#### Ints

#### Objects

### Select features

One feature

## Exploratory Data Analysis

## Processing

## Data Visualization/Communication of Results